In [3]:
import numpy as np
from sklearn.model_selection import train_test_split
x, y = np.arange(10).reshape((5,2)),range(5)
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [7]:
list(y)

[0, 1, 2, 3, 4]

In [17]:
x_train, x_test, y_train, y_test = train_test_split(x,y,train_size = 0.6,random_state=2)
x_train

array([[2, 3],
       [6, 7],
       [0, 1]])

In [19]:
x_test

array([[4, 5],
       [8, 9]])

In [21]:
y_train

[1, 3, 0]

In [23]:
y_test

[2, 4]